# Generated by Django 2.0.8 on 2018-08-08 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subreddit_id', models.CharField(max_length=10)),
                ('subreddit', models.CharField(max_length=255)),
                ('link_id', models.CharField(max_length=10)),
                ('parent_id', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=10, unique=True)),
                ('author', models.CharField(max_length=255)),
                ('body', models.CharField(max_length=1000)),
                ('score', models.SmallIntegerField()),
                ('downs', models.SmallIntegerField()),
                ('edited', models.BooleanField()),
                ('permalink', models.CharField(max_length=1000)),
                ('created_utc', models.DateTimeField()),
            ],
        ),
    ]
